# Generated by Django 4.2.15 on 2025-07-06 13:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0005_menupost_blurb_menupost_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dish',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('menu_post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dishes', to='website.menupost')),
            ],
        ),
    ]
