# Generated by Django 4.2.15 on 2025-07-06 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0006_dish'),
    ]

    operations = [
        migrations.AddField(
            model_name='menupost',
            name='category',
            field=models.CharField(choices=[('breakfast', 'Breakfast'), ('lunch', 'Lunch'), ('dinner', 'Dinner'), ('snacks', 'Snacks'), ('drinks', 'Drinks'), ('dessert', 'Dessert'), ('combo', 'Combo Meals')], default='lunch', max_length=20),
        ),
    ]
