# Generated by Django 4.2.15 on 2025-07-07 03:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0008_menureview'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menupost',
            name='category',
        ),
        migrations.DeleteModel(
            name='MenuReview',
        ),
    ]
