# Generated by Django 4.2.15 on 2025-07-07 16:36

from django.db import migrations
import django_summernote.fields


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0009_remove_menupost_category_delete_menureview'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menupost',
            name='blurb',
        ),
        migrations.AlterField(
            model_name='menupost',
            name='content',
            field=django_summernote.fields.SummernoteTextField(blank=True),
        ),
    ]
