# Generated by Django 4.2.15 on 2025-07-08 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0010_remove_menupost_blurb_alter_menupost_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='websiteimage',
            name='name',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
