# Generated by Django 4.2.15 on 2025-07-10 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0005_remove_room_room_number_remove_roombooking_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='room_type',
            field=models.CharField(choices=[('standard', 'Standard Room'), ('deluxe', 'Deluxe Room'), ('family', 'Family Room'), ('suite', 'Luxury Suite'), ('garden', 'Garden View Room'), ('poolside', 'Poolside Room'), ('executive', 'Executive Room'), ('honeymoon', 'Honeymoon Suite'), ('heritage', 'Heritage Room'), ('tent', 'Tent Cottage')], max_length=20),
        ),
    ]
