# Generated by Django 4.2.15 on 2025-07-10 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0006_alter_room_room_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='image',
        ),
        migrations.AddField(
            model_name='room',
            name='image_url',
            field=models.URLField(default='standard room', max_length=500),
            preserve_default=False,
        ),
    ]
