# Generated by Django 4.2.15 on 2025-07-10 04:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0012_alter_websiteimage_category'),
        ('bookings', '0007_remove_room_image_room_image_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='image_url',
        ),
        migrations.AddField(
            model_name='room',
            name='image',
            field=models.ForeignKey(blank=True, limit_choices_to={'category': 'room_image'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='room_images', to='website.websiteimage'),
        ),
        migrations.AddField(
            model_name='room',
            name='max_occupancy',
            field=models.PositiveIntegerField(default=2),
        ),
        migrations.AddField(
            model_name='room',
            name='num_beds',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='room',
            name='title',
            field=models.CharField(max_length=200),
        ),
    ]
