# Generated by Django 4.2.15 on 2025-07-12 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0008_remove_room_image_url_room_image_room_max_occupancy_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='roombooking',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('cancelled', 'Cancelled')], default='pending', max_length=10),
        ),
    ]
